@echo off
echo Fixing Tailwind CSS configuration...
echo.

echo Installing dependencies...
call npm install --no-audit --no-fund --loglevel=error

echo Removing node_modules/.cache directory...
rmdir /s /q node_modules\.cache

echo Clearing Next.js cache...
rmdir /s /q .next

echo Making sure Tailwind and PostCSS are installed...
call npm install -D tailwindcss@latest postcss@latest autoprefixer@latest

echo Checking Node.js version...
node --version

echo Creating new Tailwind configuration...
npx tailwindcss init -p

echo Running development server...
start http://localhost:3001
npm run dev
